### ISSUE TITLE
On OneCloud, enable parallel CI test execution for each PR 

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/vsphere-storage-for-docker#1323]
As a developer I should be able to get CI test run result in 30 minutes. 

Currently, each PR push queues up and waits for earlier runs to complete. 

- [x] ~dedicated testbed is required~ (being tracked at #1899)

- [ ] Update validate-and-serialize.sh (#1902)

- [x] Plugin push should append build number (currently it is tagged with `latest-CI` (https://github.com/vmware/docker-volume-vsphere/pull/1900)

- [ ] Update .drone.yml to read correct testbed information.

**Comment by shaominchen** [comment]
We will take care of this in next release.

**Comment by shaominchen** [comment]
This CI improvement can potentially improve developer productivity significantly. Marking as mustfix for Kubecon.

**Comment by shuklanirdesh82** [comment]
individual task has been created closing this epic issue.
