### ISSUE TITLE
Automate the process to cut the release

### ISSUE THREAD

**Issue by tusharnt** [vmware/vsphere-storage-for-docker#1966]
- [ ] Use Releases API to automate some of the steps that are done manually while [cutting the release](https://github.com/vmware/docker-volume-vsphere/blob/master/CONTRIBUTING.md) -
 https://developer.github.com/v3/repos/releases/
- [ ]  Automate upload of release binaries to bintray - https://bintray.com/docs/api/ 
- [ ]  Automate upload of the managed plugin to docker store - https://docs.docker.com/docker-store/
- [ ]  Automate the content on StorageHub to reflect the latest documentation- tracked by #1965  
- [ ]  Automate impersonate as a customer to download vib and plugins after the release is cut and perform basic/upgrade testing.

**Comment by tusharnt** [comment]
Not a high priority at the moment.

**Comment by shuklanirdesh82** [comment]
we shall reopen if needed in future.
